### ISSUE TITLE
Pobieranie podzbioru wypowiedzi

### ISSUE THREAD

**Issue by pbiecek** [mi2-warsaw/sejmRP#12]
@smudap czy mamy funkcję do pobierania tylko podzbioru wypowiedzi posłów.
Np. tylko dla 8 kadencji albo tylko z tego roku?
Dla głosowań jest get_filtered_votes() ale dla wypowiedzi nie widzę niczego podobnego.

**Comment by smudap** [comment]
Nie implementowałem tego typu funkcji. Ale funkcje get_statements_table() i filter() z dplyra załatwiają ten problem.

**Comment by pbiecek** [comment]
Niestety nie załatwiają,
Ponieważ aby użyć filter trzeba najpierw pobrać całą tabelę, która jest duża i szybko rośnie.
Przy słabszych łączach nie da się jej pobrać.



Dnia 22.10.2016 o godz. 18:36 Piotr Smuda <notifications@github.com> napisał(a):

**Comment by smudap** [comment]
No chyba że tak. Postaram się w takim razie dopisać taką funkcję w weekend jak będę miał chwilę. Może też pomyślę o dodaniu innych funkcji, którę używam w projekcie z wizualizacji, a nie ma ich w pakiecie.

**Comment by mikolajjj** [comment]
Piotr, jeśli pozwolisz to ja spróbowałbym dopisać taką funkcję. A w zasadzie funkcje: pobieranie po latach, po kadencjach, ew. po posiedzeniach (zakresach). Do weekendu się nie wyrobię, ale do końca kolejnego tygodnia mogę spróbować. Mógłbyś skupić się na dodaniu tych dodatkowych funkcji, o których piszesz

**Comment by smudap** [comment]
Tomek, Przemkowi chodzi chyba by ta funkcja pojawiła się asap, bo w danym momencie mamy projekt na studiach z tymi danymi. To jest defacto przełożenie funkcji get_fixed_votes() na tabelkę ststements ;)

**Comment by mikolajjj** [comment]
Wrzuciłem funkcję, proszę o przetestowanie

**Comment by pbiecek** [comment]
@mikolajjj Dzięki za tę funkcję,
Brakowało dokumentacji w Rd i eksportu (po utworzeniu pliku R trzeba jeszcze uruchomić funkcje devtools::document() któ®a konwertuje dokumentacje w roxygen na dokumentacje Rd), to poprawiłem w ostatnim commit.

Mam jednak problem z użyciem tej funkcji, nie działają u mnie poniższe instrukcje, każda kończy się błędem.

get_filtered_statements(terms_of_office = "8")
get_filtered_statements(terms_of_office = 8)
get_filtered_statements(terms_of_office = c("7","8"))
get_filtered_statements(terms_of_office = c(7,8))
get_filtered_statements(dates = c("2015-11-01", "2016-11-01"))

Czy należy z niej inaczej korzystać?
Może dodać przykłady użycia w sekcji examples?

**Comment by mikolajjj** [comment]
Próbowałem dziś rano zrobić commit z poprawioną wersją, ale z powodu jakiegoś konfliktu się to nie udało. Właśnie piszę maila do Piotra w tej sprawie, dodaję Przemka w DW

**Comment by mikolajjj** [comment]
I jeszcze jedna sprawa: tabela 'counter" w mojej bazie wymagała zwiększenia rozmiaru pola 'what'. Zbyt mały rozmiar powodował błędy

**Comment by smudap** [comment]
Błędy w wywołaniu tych funkcji są z tego powodu, że kolumna what w tabelce counter ma zbył małą pojemność znaków. Trzeba ją zwiększyć np. do 20 + z tego powodu, że liczby podajesz jako napisy.
