### ISSUE TITLE
How to get club membership for each deputy?

### ISSUE THREAD

**Issue by adamryczkowski** [mi2-warsaw/sejmRP#14]
The only way I can get this relation is via the table `votes` field `club`, but then I might get more than one distinct club for each deputy. I might work from there, but maybe there is a more straightforward way to get it.

**Comment by mikolajjj** [comment]
Deputies may change affiliation during a term, so only some of them have distinct club while the others have up to several

**Comment by tmikolajczyk** [comment]
zamykam
